name: Deploy Bun.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-docker-username/your-bun-app:latest .
          docker push your-docker-username/your-bun-app:latest

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} # Or use a key
          script: |
            docker pull your-docker-username/your-bun-app:latest
            docker stop bun-app || true
            docker rm bun-app || true
            docker run -d --name bun-app -p 3000:3000 your-docker-username/your-bun-app:latest
